//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackOnTrack.WebProxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BackOnTrack.WebProxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;title&gt;Page blocked - Back on Track&lt;/title&gt;
        ///    &lt;link
        ///      rel=&quot;shortcut icon&quot;
        ///      href=&quot;data:image/x-icon;base64,AAABAAYAAAAAAAEAIAAsHwAAZgAAAICAAAABACAAKAgBAJIfAABAQAAAAQAgAChCAAC6JwEAMDAAAAEAIACoJQAA4mkBACAgAAABACAAqBAAAIqPAQAQEAAAAQAgAGgEAAAyoAEAiVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAe80lEQVR42u3deXAk130f8O+cGNwLYAHsffFakrssiqZkaSRRonzFluOSJbtkJXZFqSR2IjmO43SlbMuOHdslWdZLSWUnMiXbZblUtKWQNGXRPFYiKYbkDo/FHiSwWNxY3NfMYO6eq/vlDwzE3dnuwQzQ3a97+vep4j/9hq9/PYv+zev3Xr8HEEJcy2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlockedPage {
            get {
                return ResourceManager.GetString("BlockedPage", resourceCulture);
            }
        }
    }
}
